version: 0.1.{build}

branches:
  only:
    - master

os: Visual Studio 2015
platform: Any CPU
configuration: Release

before_build:
  - ps: nuget restore Pleer.Net.sln

build:
  project: Pleer.Net.sln
  publish_nuget: true
  publish_nuget_symbols: true

init:
  - ps: $env:GIT_HASH = $env:APPVEYOR_REPO_COMMIT.Substring(0, 7)

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-$(GIT_HASH)-$(APPVEYOR_REPO_BRANCH)'

shallow_clone: true

test:
  assemblies:
    - Pleer.Net.Tests.dll

artifacts:
  - path: '**\Pleer.Net*.nupkg'

deploy:
  - provider: GitHub
    name: github_release
    auth_token:
      secure: B8gZhfAArOTHNESIhicNlL/BOgz3dBlqV/TGFReQHe5EVIjhtFWbjc3mvRD83DaI
    artifact: /^Pleer.Net.*\.nupkg$/
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true
  
  - provider: NuGet
    name: nuget_release
    api_key:
      secure: dneZawAI0W9FhzS0HchqG+lYctcJbuJ+Yv/77lnVuTWX4H/NeHPW06Daw3fxHekY
    artifact: /^Pleer.Net.*\.nupkg$/
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true
